### ISSUE TITLE
Export Problem in WindowsUI

### ISSUE THREAD

**Issue by bhavneetsinghthakur** [xBimTeam/XbimWindowsUI#2]
hi i am facing problem in export when i convert ifc to wexbim and test it on WebUI
it throws error  

uncaught exception: Style index not found.

when file size less ( i.e 400kb) then it works fine but if size is greater that time it throws error

my ifc file link plz check it tell me the problem

Download link 
http://we.tl/hA2UQkcfjs

**Comment by LloydPickering** [comment]
Maybe one for Martin? (Assigned)

**Comment by bhavneetsinghthakur** [comment]
Hi martin1cerny You Fix this Issue or Still Working On It.

**Comment by martin1cerny** [comment]
This issue has been fixed in the WexBIM creation code. If you regenerate WexBIM file using the latest geometry engine it will work all right. Sorry for the late response, it has been fixed while ago.

**Comment by minhnguyenlinknode** [comment]
Hi, I have the same problem. I have updated the latest Geometry Engine from Nuget packages but it still does not work. Any idea?

**Comment by minhnguyenlinknode** [comment]
I have updated the Xbim.WeXplorer (file xbim-viewer.debug.bundle.js) and it works now. THanks.

**Comment by mikeduberry** [comment]
Hi, I am new to this and have the same problem. I am using the latest xbim-viewer.debug.bundle.js from XbimWebUI comited on 2 Oct,  Xbim.Geometry 3.1.14. The example FourWalls.ifc converts and displays OK, but the example LakesideRestaurant.ifc converts but results in the uncaught exception: Style index not found error.

My code behind is...

[Default.aspx.cs.zip](https://github.com/xBimTeam/XbimWindowsUI/files/65888/Default.aspx.cs.zip)

Can you guys please advise, many thanks.

**Comment by CBenghi** [comment]
@mikeduberry I think you should be asking this question under WebUI; WindowsUI only exposes UI to primitives defined in other packages for this issue.

**Comment by mikeduberry** [comment]
Thanks for that, humble apologies.
